#include "buzzer.h"

/* TIM1_CH3 drives the buzzer pin (PC2). Generated by CubeMX in main.c. */
extern TIM_HandleTypeDef htim1;

/* counter: 1 MHz, ARR: 399, PWM period: 400 ticks
 * 1 MHz / 400 = 2.5 kHz
 * 20 =  5% duty */
#define BUZZER_VOLUME_CCR 20U

// How many more ms does the buzzer need to sound
static volatile uint32_t buzzer_timeout = 0U;

// Silence the buzzer
void buzzer_off(void)
{
    buzzer_timeout = 0U;
    __HAL_TIM_SET_COMPARE(&htim1, TIM_CHANNEL_3, 0U);
}

// Start to ring the buzzer
void buzzer_alert(uint32_t duration_ms) {
    __HAL_TIM_SET_COMPARE(&htim1, TIM_CHANNEL_3, BUZZER_VOLUME_CCR);
    buzzer_timeout = duration_ms;
}

/* Called once per ms from the timer interrupt. Counts the buzzer_timeout down and
 * silences the buzzer when the time is up. */
void buzzer_tick_1ms(void) {
    if (buzzer_timeout > 0U) {
        buzzer_timeout--;

        if (buzzer_timeout == 0U) {
            buzzer_off();
        }
    }
}
